name: Docker Build and Push with Dynamic Tag

on:
  push:
    branches:
      - main

env:
  REPO_NAME: poridhi
  IMAGE_NAME: todo-backend
  VERSION: 2.1

jobs:
  build-and-push:
    runs-on: arc-runner-set
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate dynamic tag
        id: tag
        run: |
          DYNAMIC_TAG="v${VERSION}.${GITHUB_RUN_NUMBER}-${GITHUB_SHA::7}"
          echo "DYNAMIC_TAG=${DYNAMIC_TAG}" >> $GITHUB_ENV
          echo "Generated tag: ${DYNAMIC_TAG}"

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image
        run: |
          # Build the image
          docker build -t ${REPO_NAME}/${IMAGE_NAME}:${DYNAMIC_TAG} -t ${REPO_NAME}/${IMAGE_NAME}:latest .
          
          # Push the images
          docker push ${REPO_NAME}/${IMAGE_NAME}:${DYNAMIC_TAG}
          docker push ${REPO_NAME}/${IMAGE_NAME}:latest

      - name: Print success message
        run: |
          echo "Successfully built and pushed Docker image"
          echo "Image: ${REPO_NAME}/${IMAGE_NAME}:${DYNAMIC_TAG}"