# In your GitHub workflow file (.github/workflows/example.yml)
name: My Workflow
on: [push]
jobs:
  build:
    runs-on: arc-runner-set  # Use this label to run on your self-hosted runner
    steps:
      - uses: actions/checkout@v2
      - name: Run your task
        run: echo "Running on self-hosted runner!"