name: My Workflow
on: [push]
jobs:
  build:
    runs-on: arc-runner-set
    steps:
      - uses: actions/checkout@v4
      
      # Add kubectl command
      - name: Check Kubernetes nodes
        run: kubectl get nodes