name: Docker Build and Push with Dynamic Tag

on:
  push:
    branches:
      - main

env:
  REPO_NAME: poridhi
  IMAGE_NAME: todo-backend
  VERSION: 2.1

jobs:
  build-and-push:
    runs-on: arc-runner-set
    
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Install make
      - name: Install make
        run: |
          sudo apt-get update
          sudo apt-get install -y make

      # Step 3: Setup Docker
      - name: Setup Docker
        run: |
          sudo systemctl start docker || true
          sudo systemctl status docker
          sudo chmod 666 /var/run/docker.sock || true
          docker info

      # Step 4: Login to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 5: Build and Push using Makefile with dynamic tag
      - name: Build and Push Docker image
        run: |
          make build-push

      # Step 6: Print success message
      - name: Print success message
        run: |
          echo "Successfully built and pushed Docker image"